name: e_leaningapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_core: ^3.0.0
  file_picker: ^5.2.10
  iconly: ^1.0.1
  flutter_dropdown_search: ^0.0.4
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0
  http: ^1.2.0
  flutter_facebook_auth: ^6.0.4
  flutter_form_builder: ^9.3.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^0.0.1
  animated_text_kit: ^4.2.2

  palette_generator: ^0.3.3+3
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  mailer: ^6.1.0
  numeral: ^3.0.0
  image_cropper: ^7.0.5
  uuid: ^4.5.0
  colorful_progress_indicators: ^1.0.2
  vertical_scrollable_tabview: ^0.1.1
  colorful_circular_progress_indicator: ^0.0.2
  random_avatar: ^0.0.8
  flutter_svg: ^2.0.10+1
  pull_to_refresh: ^2.0.0
  dotted_border: ^2.1.0
  animated_background: ^2.0.0
  flutter_cache_manager: ^3.3.2
  firebase_messaging: ^15.0.3
  expandable: ^5.0.1
  linkfy_text: ^1.1.6
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.1+2
  carousel_slider: ^4.2.1
  awesome_notifications: ^0.9.3+1
  loading_btn: ^1.0.3
  animated_theme_switcher: ^2.0.8
  photo_view: ^0.15.0
  provider: ^6.1.2
  better_player:
    path: packages/better_player
  flutter_downloader: ^1.11.8
  retry: ^3.1.2
  reorderables: ^0.6.0
  dot_navigation_bar: ^1.0.2
  permission_handler: ^11.3.1
  flutter_download_manager:
    path: packages/flutter_download_manager
  fl_chart: ^0.68.0
  go_router: ^14.2.7
  sliding_up_panel: ^2.0.0+1
  flutter_stripe: ^11.0.0
  get_it: ^7.7.0
  fluttertoast: ^8.2.8
  insta_assets_picker:
    path: packages/insta_assets_picker
  flutter_slidable: ^3.1.1
  lottie: ^3.1.2
  tab_indicator_styler: ^2.0.0
  dio: ^5.7.0
  zoom_tap_animation: ^1.1.0
  preload_page_view: ^0.2.0
  flutter_bloc: ^8.1.6
  flutter_isolate: ^2.1.0
  injectable: ^2.5.0
  cached_video_player_plus:
    git:
      url: https://github.com/rignaneseleo/cached_video_player_plus.git
  audio_video_progress_bar: ^2.0.3
  tapped: ^2.0.0
  # map取值
  safemap: ^2.1.0
  # 加载动画库
  flutter_spinkit: ^5.2.1
  video_player: ^2.9.2
  video_compress_v2: ^1.0.0+1
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  khqr_widget: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: any
  freezed: any
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/output.mp4
    - assets/icons/tv-icon.png
    - assets/icons/
    - assets/images/

  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: fonts/NotoSansKhmer-Regular.ttf
        - asset: fonts/NotoSansKhmer-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/playstore-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/playstore-icon.png"
