// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAITTuZb2cXoZdtLuGzPruXFHt2S91oNoc',
    appId: '1:958733498686:web:bd7f00a4cfb88db7f0d46f',
    messagingSenderId: '958733498686',
    projectId: 'elearning-app-a6e15',
    authDomain: 'elearning-app-a6e15.firebaseapp.com',
    storageBucket: 'elearning-app-a6e15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEatVnKqV7uiRj71fGHStv-eyP6Wd3BUw',
    appId: '1:958733498686:android:ec919230808af1a2f0d46f',
    messagingSenderId: '958733498686',
    projectId: 'elearning-app-a6e15',
    storageBucket: 'elearning-app-a6e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOsQ8w_4VQuKXxcM1hPL-ESBbtF3Ea0P4',
    appId: '1:958733498686:ios:2b04893acc6ed76ef0d46f',
    messagingSenderId: '958733498686',
    projectId: 'elearning-app-a6e15',
    storageBucket: 'elearning-app-a6e15.appspot.com',
    iosBundleId: 'com.example.eLeaningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOsQ8w_4VQuKXxcM1hPL-ESBbtF3Ea0P4',
    appId: '1:958733498686:ios:d879e2674316114ef0d46f',
    messagingSenderId: '958733498686',
    projectId: 'elearning-app-a6e15',
    storageBucket: 'elearning-app-a6e15.appspot.com',
    iosBundleId: 'com.example.eLeaningapp.RunnerTests',
  );
}
